install.packages("dplyr")
install.packages("ggplot2")
install.packages("magrittr")
install.packages(data.table)
library(data.table)
library(ggplot2)
library(dplyr)
library(magrittr)

dados <- read.table("household_power_consumption.txt", header = TRUE,sep = ";", dec = ",")
dados2 <- subset(dados,Date=="1/2/2007")
dados3 <- subset(dados,Date=="2/2/2007")
dadosfinais <- bind_rows(dados2,dados3)
dadosfinais$Global_active_power <- as.numeric(dadosfinais$Global_active_power)
dadosfinais$Voltage <- as.numeric(dadosfinais$Voltage)
dadosfinais$Global_reactive_power <- as.numeric(dadosfinais$Global_reactive_power)
dadosfinais$Sub_metering_1 <- as.numeric(dadosfinais$Sub_metering_1)
dadosfinais$Sub_metering_2 <- as.numeric(dadosfinais$Sub_metering_2)
dadosfinais$Sub_metering_3 <- as.numeric(dadosfinais$Sub_metering_3)
dadosfinais$Date = as.Date(dadosfinais$Date, '%d/%m/%Y')
dadosfinais$Date_and_Time <- strptime(paste(dadosfinais$Date, dadosfinais$Time), "%Y-%m-%d %H:%M:%S")
str(dadosfinais)
par(mfrow = c(2, 2))
plot(dadosfinais$Date_and_Time, dadosfinais$Global_active_power,type = "l",xlab = "",ylab = "Global Active Power") 
plot(dadosfinais$Date_and_Time, dadosfinais$Voltage,type = "l",xlab = "",ylab = "Voltage") 
plot(dadosfinais$Date_and_Time, dadosfinais$Sub_metering_1,type = "l",xlab = "",ylab = "Energy sub metering")
lines(dadosfinais$Date_and_Time, dadosfinais$Sub_metering_2, col = "red")
lines(dadosfinais$Date_and_Time, dadosfinais$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"),c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd = 1, bty = "n")
plot(dadosfinais$Date_and_Time, dadosfinais$Global_reactive_power,type = "l",xlab = "",ylab = "Global reactive power") 


dev.copy(png, file="plot4.png")
dev.off()
