install.packages("dplyr")
install.packages("ggplot2")
install.packages("magrittr")
install.packages("multipanelfigure")
install.packages(data.table)
library(data.table)
library(ggplot2)
library(dplyr)
library(multipanelfigure)
library(magrittr)

dados <- read.table("household_power_consumption.txt", header = TRUE,sep = ";",dec = ".",na.strings = "?")
dados2 <- subset(dados,Date=="1/2/2007")
dados3 <- subset(dados,Date=="2/2/2007")
dadosfinais <- bind_rows(dados2,dados3)
dadosfinais$Sub_metering_1 <- as.numeric(dadosfinais$Sub_metering_1)
dadosfinais$Sub_metering_2 <- as.numeric(dadosfinais$Sub_metering_2)
dadosfinais$Sub_metering_3 <- as.numeric(dadosfinais$Sub_metering_3)

dadosfinais$Date = as.Date(dadosfinais$Date, '%d/%m/%Y')
dadosfinais$Date_and_Time <- strptime(paste(dadosfinais$Date, dadosfinais$Time), "%Y-%m-%d %H:%M:%S")
str(dadosfinais)

plot(dadosfinais$Date_and_Time, dadosfinais$Sub_metering_1,type = "l",xlab = "",ylab = "Energy sub metering")
lines(dadosfinais$Date_and_Time, dadosfinais$Sub_metering_2, col = "red")
lines(dadosfinais$Date_and_Time, dadosfinais$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"),c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd = 1, bty = "n")

dev.copy(png, file="plot3.png")
dev.off()
